name: test
on:
  [workflow_dispatch]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
      - name: build and push
        run: |
          # echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u alpellegri --password-stdin
          # docker build . --tag ghcr.io/alpellegri/test:latest
          # docher push ghcr.io/alpellegri/test:latest
