name: test
on:
  [workflow_dispatch]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build and push
        run: |
          echo ${{ secrets.CH_PAT }} | docker login --username alpellegri --password-stdin
          docker build . --tag ghcr.io/alpellegri/test:latest
          docher push ghcr.io/alpellegri/test:latest
