name: test
on:
  [workflow_dispatch]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Group of log lines
        run: |
            echo "::group::My title"
            echo ${{ secrets.GH_PAT }}
            echo "::endgroup::"
      - name: build and push
        run: |
          echo ${{ secrets.GH_PAT }}
          # echo ${{ secrets.GH_PAT }} | docker login --username alpellegri --password-stdin
          # docker build . --tag ghcr.io/alpellegri/test:latest
          # docher push ghcr.io/alpellegri/test:latest
