name: ghcr
# run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './store'
    permissions:
      contents: read
    steps:
      - name: checkout
        uses: action/checkout@v4
