name: test
on:
  [workflow_dispatch]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          repository: alpellegri/docker-test
          token: ${{ secrets.GH_PAT }}
          ref: master
